package com.xiaoji.authface.service;


import com.xiaoji.authface.domain.SysUser;
import com.xiaoji.authface.repository.SysUserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service  // 接口和实现处都需要添加@Service注解
public class UserService implements IUserService {
    /**
     *  @ Autowired
     *  this means to get the bean called userRepository
     *  which is auto-generated by Spring, we will use it to handle the data
     */
    @Autowired  // Field injection is not recommended
    private SysUserRepository userRepository;

    // 注册用户
    @Override
    public SysUser register(String name, String nickname, String password){

        SysUser sysUser = new SysUser();
        sysUser.setUserName(name);
        sysUser.setNickName(nickname);
        sysUser.setUserType("移动用户");
        sysUser.setPassword(password);
        userRepository.save(sysUser);
        return sysUser;
    }

    // 账号登录
    @Override
    public String accountLogin(String name, String password) {
        List<SysUser> sysUsers = userRepository.findSysUserByUserNameAndPassword(name, password);
        if(!sysUsers.isEmpty()){
            return  sysUsers.toString();
        }else{
            return "FAILED";
        }
    }
}
