# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xiaoji

# 挂载目录
VOLUME /home/xiaoji
# 创建目录
RUN mkdir -p /home/xiaoji
# 指定路径
WORKDIR /home/xiaoji
# 复制jar文件到路径
COPY ./jar/xaioji-gateway.jar /home/xiaoji/xiaoji-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","xiaoji-gateway.jar"]